[deps]
BitemporalPostgres = "e513cd14-23e6-48df-acf1-d9bc8fa5674b"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LifeInsuranceDataModel = "4892898e-25d7-46ce-b5c3-dea2164303ac"
LifeInsuranceProduct = "492f22fc-54e6-4f0f-bb9b-bacd199f5046"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightPostgreSQL = "4327cdd6-4902-11ea-0272-430cea0431bd"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
ToStruct = "43ec2cc1-0e50-5406-a854-b7ff8fdb8dad"

[compat]
SearchLight = "2"
